package com.rw.directories.dao;

public interface SQLQueries {
    public static final String PARAMS_INFO = "SELECT CURRENT_TIMESTAMP AS UPDATED_ON, ID, TYPE, CODE, VALUE FROM ETICKET.PARAMETERS";
    public static final String PARAM_INFO = "SELECT CURRENT_TIMESTAMP AS UPDATED_ON, ID, TYPE, CODE, VALUE FROM ETICKET.PARAMETERS WHERE CODE=:CODE";

    public static final String COUNTRIES_INFO = "SELECT CURRENT_TIMESTAMP AS UPDATED_ON, ID, CODE, TICKET_SELLING_ALLOWED, TIME_ZONE, NAME_{0} AS NAME, DEPARTURE_MSG_{0} AS DEPARTURE_MSG, ARRIVAL_MSG_{0} AS ARRIVAL_MSG, STATION_SELECT_PRIORITY, IS_GLOBAL_PRICE, FREE_TICKET_AGE, CHILDREN_TICKET_AGE FROM ETICKET.COUNTRIES";
}
